name: cicd_demo

on:
  push:
    branches:
      - main

jobs:
  registerPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Register package step."

  change:
    name: Change Request Attributes
    runs-on: ubuntu-latest
    needs: registerPackage

    steps:
      - name: ServiceNow DevOps Get Change
        uses: ServiceNow/servicenow-devops-get-change@v6.3.0
        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          devops-integration-user-name: ${{ secrets.SN_USERNAME }}
          devops-integration-user-password: ${{ secrets.SN_PASSWORD }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJson(github) }}
          change-details: |
            {
              "short_description": "Change from GitHub commit",
              "description": "Triggered automatically on push to main",
              "assignment_group": "DevOps",
              "requested_by": "admin"
            }
