name: cicd_demo

on:
  push:
    branches:
      - main

jobs:
  change:
    runs-on: ubuntu-latest

    steps:
      - name: change
        uses: ServiceNow/servicenow-devops-get-change@v6.3.0
        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJson(github) }}
          change-details: |
            {
              "short_description": "Auto change8",
              "description": "Triggered from GitHub"
            }
